version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - DB_URI=mongodb://root:password@localhost:27018/?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./server:/server:cached

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/client:cached

volumes:
  mongo_data:
