# version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    env_file:
      - /server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=apihw
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./server/.env
    environment:
      - DB_URI=mongodb://mongo:27017/apihw
    depends_on:
      - mongo
    volumes:
      - ./server:/server:cached

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    volumes:
      - ./client:/client:cached

volumes:
  mongo_data:


networks:
  app-network:
    driver: bridge
